---
name: maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  #disabled
  .maven:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Build and test
        run: mvn verify
